name: repo_viewer

description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.2.0
  dartz: ^0.10.1
  dio: ^5.1.2
  flash: ^3.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  oauth2: ^2.0.1
  webview_flutter: ^4.2.1
  riverpod: ^2.3.6

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  lint: ^2.1.2

flutter:
  uses-material-design: true
